age = int(input("give me your age"))
print(f"You are currently {age}.")
print(f"In 10 years, you'll be {age + 10}")
print(f"In 20 years, you'll be {age + 20}")
print(f"In 30 years, you'll be {age+ 30}")
